image: node:10.6.0

cache:
  paths:
  - node_modules/
  - .yarn

before_script:
  - yarn install

stages:
  - lint
  - bundle
  - test
  - performance

lint:
  stage: lint
  script:
   - npm run eslint

bundle:
  stage: bundle
  script:
   - npm run build

test:
  stage: test
  script:
   - npm test

performance:
  stage: performance
  script:
   - npm run perf
